kind: PersistentVolume
apiVersion: v1
metadata:
  name: firewall-volume
  namespace: devx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hgfs/BiDa_Shared_Volume"