kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: firewall-volume-claim
  namespace: devx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
