apiVersion: apps/v1
kind: Deployment
metadata:
  name: devx-file-listener
  namespace: devx
spec:
  selector:
    matchLabels:
      app: devx-file-listener
  template:
    metadata:
      labels:
        app: devx-file-listener
      annotations:
        io.cadvisor.metric.prometheus: /etc/custom-metrics/definition.json

    spec:
      volumes:
       - name: config
         emptyDir:

       - name: firewall-volume
         persistentVolumeClaim:
           claimName: firewall-volume-claim

      initContainers:
       - name: init-myservice
         image: busybox
         imagePullPolicy: Never
         command: ['sh', '-c', 'echo "{\"endpoint\": \"http://192.168.228.134:9000/metrics\"}" > /etc/custom-metrics/definition.json']

         env: 
         - name: POD_IP
           valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
         

         volumeMounts:
         - name: config
           mountPath: /etc/custom-metrics

      containers:
       - name: devx-file-listener
         image: devx/filewatcher:v1.0.4
         imagePullPolicy: Never
         ports:
         - containerPort: 8080
           hostPort: 9000

         env:
         - name: ROLE
           value: "publisher"
         envFrom:
         - configMapRef:
             name: kafka-config
         - configMapRef:
             name: filex-config

         volumeMounts:
         - name: config
           mountPath: /etc/custom-metrics
         - name: firewall-volume
           mountPath: /data/

         resources:
           requests:
             cpu: 125m
             memory: 64Mi
           limits:
             #cpu: 500m
             memory: 128Mi

