apiVersion: apps/v1
kind: Deployment
metadata:
  name: devx-rules-parser
  namespace: devx
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "init-myservice",
            "image": "busybox",
            "command": ["sh", "-c", "sleep 20"]
        }
    ]'

spec:
  selector:
    matchLabels:
      app: devx-rules-parser
  template:
    metadata:
      labels:
        app: devx-rules-parser
    spec:
      containers:
       - name: devx-rules-parser
         image: devx/rules-parser:v1.0.0
         imagePullPolicy: Never
         env:
         - name: DEVX_RULES_KAFKA_TOPIC
           value: "ruleChangeTrigger"
         - name: DEVX_KAFKA_SERVICE_PORT
           value: "9092"
         - name: DEVX_KAFKA_SERVICE_HOST
           value: "192.168.228.134"

         resources:
           requests:
             cpu: 125m
             memory: 128Mi
           limits:
             #cpu: 500m
             memory: 256Mi

